<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="16" passed="0" failed="0" skipped="16">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-09-28T17:34:17 IST" name="Default suite" finished-at="2023-09-28T17:34:18 IST" duration-ms="694">
    <groups>
      <group name="Exclude">
        <method signature="POShipmentTestCases.TC_0056_createShipmentWithCasePackedAndSPD()[pri:0, instance:[POShipmentTestCases passed=0 failed=0 skipped=0]]" name="TC_0056_createShipmentWithCasePackedAndSPD" class="sc.testSuite.POShipmentTestCases"/>
        <method signature="POShipmentTestCases.TC_0057_createShipmentWithCasePackedAndLTL()[pri:0, instance:[POShipmentTestCases passed=0 failed=0 skipped=0]]" name="TC_0057_createShipmentWithCasePackedAndLTL" class="sc.testSuite.POShipmentTestCases"/>
        <method signature="POShipmentTestCases.TC_0058_createShipmentWithIndividualAndSPD()[pri:0, instance:[POShipmentTestCases passed=0 failed=0 skipped=0]]" name="TC_0058_createShipmentWithIndividualAndSPD" class="sc.testSuite.POShipmentTestCases"/>
        <method signature="POShipmentTestCases.TC_0059_createShipmentWithIndvidualAndLTL()[pri:0, instance:[POShipmentTestCases passed=0 failed=0 skipped=0]]" name="TC_0059_createShipmentWithIndvidualAndLTL" class="sc.testSuite.POShipmentTestCases"/>
        <method signature="POShipmentTestCases.TC_0060_addItemsToTheShipmentAndVerify()[pri:0, instance:[POShipmentTestCases passed=0 failed=0 skipped=0]]" name="TC_0060_addItemsToTheShipmentAndVerify" class="sc.testSuite.POShipmentTestCases"/>
        <method signature="POShipmentTestCases.TC_0061_verifyTheAddedUnitsValue()[pri:0, instance:[POShipmentTestCases passed=0 failed=0 skipped=0]]" name="TC_0061_verifyTheAddedUnitsValue" class="sc.testSuite.POShipmentTestCases"/>
        <method signature="POShipmentTestCases.TC_0063_verifyTheInvoiceCSValue()[pri:0, instance:[POShipmentTestCases passed=0 failed=0 skipped=0]]" name="TC_0063_verifyTheInvoiceCSValue" class="sc.testSuite.POShipmentTestCases"/>
        <method signature="POShipmentTestCases.TC_0064_verifyTheInvoiceEAValue()[pri:0, instance:[POShipmentTestCases passed=0 failed=0 skipped=0]]" name="TC_0064_verifyTheInvoiceEAValue" class="sc.testSuite.POShipmentTestCases"/>
        <method signature="POShipmentTestCases.TC_0065_verifyTheReceivedCSValue()[pri:0, instance:[POShipmentTestCases passed=0 failed=0 skipped=0]]" name="TC_0065_verifyTheReceivedCSValue" class="sc.testSuite.POShipmentTestCases"/>
        <method signature="POShipmentTestCases.TC_0066_verifyTheInvoiceCSCost()[pri:0, instance:[POShipmentTestCases passed=0 failed=0 skipped=0]]" name="TC_0066_verifyTheInvoiceCSCost" class="sc.testSuite.POShipmentTestCases"/>
        <method signature="POShipmentTestCases.TC_0066_verifyTheInvoiceEACost()[pri:0, instance:[POShipmentTestCases passed=0 failed=0 skipped=0]]" name="TC_0066_verifyTheInvoiceEACost" class="sc.testSuite.POShipmentTestCases"/>
        <method signature="POShipmentTestCases.TC_0066_verifyTheReceivedEAValue()[pri:0, instance:[POShipmentTestCases passed=0 failed=0 skipped=0]]" name="TC_0066_verifyTheReceivedEAValue" class="sc.testSuite.POShipmentTestCases"/>
        <method signature="POShipmentTestCases.TC_0067_submitPlanAndVerifyThatAmazonshipmentIsCreatedWithoutOptimization()[pri:0, instance:[POShipmentTestCases passed=0 failed=0 skipped=0]]" name="TC_0067_submitPlanAndVerifyThatAmazonshipmentIsCreatedWithoutOptimization" class="sc.testSuite.POShipmentTestCases"/>
        <method signature="POShipmentTestCases.TC_0068_submitPlanAndVerifyThatAmazonshipmentIsCreatedWithOptimization()[pri:0, instance:[POShipmentTestCases passed=0 failed=0 skipped=0]]" name="TC_0068_submitPlanAndVerifyThatAmazonshipmentIsCreatedWithOptimization" class="sc.testSuite.POShipmentTestCases"/>
      </group> <!-- Exclude -->
    </groups>
    <test started-at="2023-09-28T17:34:17 IST" name="Default test" finished-at="2023-09-28T17:34:18 IST" duration-ms="694">
      <class name="sc.testSuite.POShipmentTestCases">
        <test-method is-config="true" signature="setUp(java.lang.String, org.testng.ITestContext)[pri:0, instance:[POShipmentTestCases passed=0 failed=0 skipped=0]]" started-at="2023-09-28T17:34:17 IST" name="setUp" finished-at="2023-09-28T17:34:18 IST" duration-ms="627" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@58516c91]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Exception occured while invoking browser, Exception message:Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Exception occured while invoking browser, Exception message:Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
at org.testng.Assert.fail(Assert.java:99)
at sc.utilities.BaseSetup.setUp(BaseSetup.java:114)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="intialize()[pri:0, instance:[POShipmentTestCases passed=0 failed=0 skipped=0]]" started-at="2023-09-28T17:34:18 IST" name="intialize" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1695902658485" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- intialize -->
        <test-method signature="TC_0055_verifyShipmentSection()[pri:0, instance:[POShipmentTestCases passed=0 failed=0 skipped=0]]" started-at="2023-09-28T17:34:18 IST" name="TC_0055_verifyShipmentSection" finished-at="2023-09-28T17:34:18 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Exception occured while invoking browser, Exception message:Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Exception occured while invoking browser, Exception message:Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
at org.testng.Assert.fail(Assert.java:99)
at sc.utilities.BaseSetup.setUp(BaseSetup.java:114)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_0055_verifyShipmentSection -->
        <test-method is-config="true" signature="intialize()[pri:0, instance:[POShipmentTestCases passed=0 failed=0 skipped=0]]" started-at="2023-09-28T17:34:18 IST" name="intialize" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1695902658489" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- intialize -->
        <test-method signature="TC_0056_createShipmentWithCasePackedAndSPD()[pri:0, instance:[POShipmentTestCases passed=0 failed=0 skipped=0]]" started-at="2023-09-28T17:34:18 IST" name="TC_0056_createShipmentWithCasePackedAndSPD" finished-at="2023-09-28T17:34:18 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Exception occured while invoking browser, Exception message:Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Exception occured while invoking browser, Exception message:Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
at org.testng.Assert.fail(Assert.java:99)
at sc.utilities.BaseSetup.setUp(BaseSetup.java:114)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_0056_createShipmentWithCasePackedAndSPD -->
        <test-method is-config="true" signature="intialize()[pri:0, instance:[POShipmentTestCases passed=0 failed=0 skipped=0]]" started-at="2023-09-28T17:34:18 IST" name="intialize" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1695902658492" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- intialize -->
        <test-method signature="TC_0057_createShipmentWithCasePackedAndLTL()[pri:0, instance:[POShipmentTestCases passed=0 failed=0 skipped=0]]" started-at="2023-09-28T17:34:18 IST" name="TC_0057_createShipmentWithCasePackedAndLTL" finished-at="2023-09-28T17:34:18 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Exception occured while invoking browser, Exception message:Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Exception occured while invoking browser, Exception message:Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
at org.testng.Assert.fail(Assert.java:99)
at sc.utilities.BaseSetup.setUp(BaseSetup.java:114)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_0057_createShipmentWithCasePackedAndLTL -->
        <test-method is-config="true" signature="intialize()[pri:0, instance:[POShipmentTestCases passed=0 failed=0 skipped=0]]" started-at="2023-09-28T17:34:18 IST" name="intialize" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1695902658495" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- intialize -->
        <test-method signature="TC_0058_createShipmentWithIndividualAndSPD()[pri:0, instance:[POShipmentTestCases passed=0 failed=0 skipped=0]]" started-at="2023-09-28T17:34:18 IST" name="TC_0058_createShipmentWithIndividualAndSPD" finished-at="2023-09-28T17:34:18 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Exception occured while invoking browser, Exception message:Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Exception occured while invoking browser, Exception message:Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
at org.testng.Assert.fail(Assert.java:99)
at sc.utilities.BaseSetup.setUp(BaseSetup.java:114)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_0058_createShipmentWithIndividualAndSPD -->
        <test-method signature="TC_0059_createShipmentWithIndvidualAndLTL()[pri:0, instance:[POShipmentTestCases passed=0 failed=0 skipped=0]]" started-at="2023-09-28T17:34:18 IST" name="TC_0059_createShipmentWithIndvidualAndLTL" finished-at="2023-09-28T17:34:18 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Exception occured while invoking browser, Exception message:Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Exception occured while invoking browser, Exception message:Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
at org.testng.Assert.fail(Assert.java:99)
at sc.utilities.BaseSetup.setUp(BaseSetup.java:114)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_0059_createShipmentWithIndvidualAndLTL -->
        <test-method is-config="true" signature="intialize()[pri:0, instance:[POShipmentTestCases passed=0 failed=0 skipped=0]]" started-at="2023-09-28T17:34:18 IST" name="intialize" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1695902658498" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- intialize -->
        <test-method is-config="true" signature="intialize()[pri:0, instance:[POShipmentTestCases passed=0 failed=0 skipped=0]]" started-at="2023-09-28T17:34:18 IST" name="intialize" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1695902658500" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- intialize -->
        <test-method signature="TC_0060_addItemsToTheShipmentAndVerify()[pri:0, instance:[POShipmentTestCases passed=0 failed=0 skipped=0]]" started-at="2023-09-28T17:34:18 IST" name="TC_0060_addItemsToTheShipmentAndVerify" finished-at="2023-09-28T17:34:18 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Exception occured while invoking browser, Exception message:Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Exception occured while invoking browser, Exception message:Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
at org.testng.Assert.fail(Assert.java:99)
at sc.utilities.BaseSetup.setUp(BaseSetup.java:114)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_0060_addItemsToTheShipmentAndVerify -->
        <test-method is-config="true" signature="intialize()[pri:0, instance:[POShipmentTestCases passed=0 failed=0 skipped=0]]" started-at="2023-09-28T17:34:18 IST" name="intialize" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1695902658502" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- intialize -->
        <test-method signature="TC_0061_verifyTheAddedUnitsValue()[pri:0, instance:[POShipmentTestCases passed=0 failed=0 skipped=0]]" started-at="2023-09-28T17:34:18 IST" name="TC_0061_verifyTheAddedUnitsValue" finished-at="2023-09-28T17:34:18 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Exception occured while invoking browser, Exception message:Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Exception occured while invoking browser, Exception message:Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
at org.testng.Assert.fail(Assert.java:99)
at sc.utilities.BaseSetup.setUp(BaseSetup.java:114)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_0061_verifyTheAddedUnitsValue -->
        <test-method is-config="true" signature="intialize()[pri:0, instance:[POShipmentTestCases passed=0 failed=0 skipped=0]]" started-at="2023-09-28T17:34:18 IST" name="intialize" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1695902658505" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- intialize -->
        <test-method signature="TC_0062_verifyTheSuggestedASINQuantityValue()[pri:0, instance:[POShipmentTestCases passed=0 failed=0 skipped=0]]" started-at="2023-09-28T17:34:18 IST" name="TC_0062_verifyTheSuggestedASINQuantityValue" finished-at="2023-09-28T17:34:18 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Exception occured while invoking browser, Exception message:Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Exception occured while invoking browser, Exception message:Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
at org.testng.Assert.fail(Assert.java:99)
at sc.utilities.BaseSetup.setUp(BaseSetup.java:114)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_0062_verifyTheSuggestedASINQuantityValue -->
        <test-method is-config="true" signature="intialize()[pri:0, instance:[POShipmentTestCases passed=0 failed=0 skipped=0]]" started-at="2023-09-28T17:34:18 IST" name="intialize" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1695902658509" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- intialize -->
        <test-method signature="TC_0063_verifyTheInvoiceCSValue()[pri:0, instance:[POShipmentTestCases passed=0 failed=0 skipped=0]]" started-at="2023-09-28T17:34:18 IST" name="TC_0063_verifyTheInvoiceCSValue" finished-at="2023-09-28T17:34:18 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Exception occured while invoking browser, Exception message:Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Exception occured while invoking browser, Exception message:Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
at org.testng.Assert.fail(Assert.java:99)
at sc.utilities.BaseSetup.setUp(BaseSetup.java:114)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_0063_verifyTheInvoiceCSValue -->
        <test-method is-config="true" signature="intialize()[pri:0, instance:[POShipmentTestCases passed=0 failed=0 skipped=0]]" started-at="2023-09-28T17:34:18 IST" name="intialize" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1695902658512" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- intialize -->
        <test-method signature="TC_0064_verifyTheInvoiceEAValue()[pri:0, instance:[POShipmentTestCases passed=0 failed=0 skipped=0]]" started-at="2023-09-28T17:34:18 IST" name="TC_0064_verifyTheInvoiceEAValue" finished-at="2023-09-28T17:34:18 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Exception occured while invoking browser, Exception message:Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Exception occured while invoking browser, Exception message:Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
at org.testng.Assert.fail(Assert.java:99)
at sc.utilities.BaseSetup.setUp(BaseSetup.java:114)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_0064_verifyTheInvoiceEAValue -->
        <test-method is-config="true" signature="intialize()[pri:0, instance:[POShipmentTestCases passed=0 failed=0 skipped=0]]" started-at="2023-09-28T17:34:18 IST" name="intialize" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1695902658515" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- intialize -->
        <test-method signature="TC_0065_verifyTheReceivedCSValue()[pri:0, instance:[POShipmentTestCases passed=0 failed=0 skipped=0]]" started-at="2023-09-28T17:34:18 IST" name="TC_0065_verifyTheReceivedCSValue" finished-at="2023-09-28T17:34:18 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Exception occured while invoking browser, Exception message:Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Exception occured while invoking browser, Exception message:Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
at org.testng.Assert.fail(Assert.java:99)
at sc.utilities.BaseSetup.setUp(BaseSetup.java:114)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_0065_verifyTheReceivedCSValue -->
        <test-method is-config="true" signature="intialize()[pri:0, instance:[POShipmentTestCases passed=0 failed=0 skipped=0]]" started-at="2023-09-28T17:34:18 IST" name="intialize" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1695902658518" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- intialize -->
        <test-method signature="TC_0066_verifyTheInvoiceCSCost()[pri:0, instance:[POShipmentTestCases passed=0 failed=0 skipped=0]]" started-at="2023-09-28T17:34:18 IST" name="TC_0066_verifyTheInvoiceCSCost" finished-at="2023-09-28T17:34:18 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Exception occured while invoking browser, Exception message:Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Exception occured while invoking browser, Exception message:Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
at org.testng.Assert.fail(Assert.java:99)
at sc.utilities.BaseSetup.setUp(BaseSetup.java:114)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_0066_verifyTheInvoiceCSCost -->
        <test-method is-config="true" signature="intialize()[pri:0, instance:[POShipmentTestCases passed=0 failed=0 skipped=0]]" started-at="2023-09-28T17:34:18 IST" name="intialize" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1695902658522" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- intialize -->
        <test-method signature="TC_0066_verifyTheInvoiceEACost()[pri:0, instance:[POShipmentTestCases passed=0 failed=0 skipped=0]]" started-at="2023-09-28T17:34:18 IST" name="TC_0066_verifyTheInvoiceEACost" finished-at="2023-09-28T17:34:18 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Exception occured while invoking browser, Exception message:Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Exception occured while invoking browser, Exception message:Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
at org.testng.Assert.fail(Assert.java:99)
at sc.utilities.BaseSetup.setUp(BaseSetup.java:114)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_0066_verifyTheInvoiceEACost -->
        <test-method is-config="true" signature="intialize()[pri:0, instance:[POShipmentTestCases passed=0 failed=0 skipped=0]]" started-at="2023-09-28T17:34:18 IST" name="intialize" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1695902658525" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- intialize -->
        <test-method signature="TC_0066_verifyTheReceivedEAValue()[pri:0, instance:[POShipmentTestCases passed=0 failed=0 skipped=0]]" started-at="2023-09-28T17:34:18 IST" name="TC_0066_verifyTheReceivedEAValue" finished-at="2023-09-28T17:34:18 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Exception occured while invoking browser, Exception message:Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Exception occured while invoking browser, Exception message:Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
at org.testng.Assert.fail(Assert.java:99)
at sc.utilities.BaseSetup.setUp(BaseSetup.java:114)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_0066_verifyTheReceivedEAValue -->
        <test-method is-config="true" signature="intialize()[pri:0, instance:[POShipmentTestCases passed=0 failed=0 skipped=0]]" started-at="2023-09-28T17:34:18 IST" name="intialize" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1695902658528" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- intialize -->
        <test-method signature="TC_0067_submitPlanAndVerifyThatAmazonshipmentIsCreatedWithoutOptimization()[pri:0, instance:[POShipmentTestCases passed=0 failed=0 skipped=0]]" started-at="2023-09-28T17:34:18 IST" name="TC_0067_submitPlanAndVerifyThatAmazonshipmentIsCreatedWithoutOptimization" finished-at="2023-09-28T17:34:18 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Exception occured while invoking browser, Exception message:Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Exception occured while invoking browser, Exception message:Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
at org.testng.Assert.fail(Assert.java:99)
at sc.utilities.BaseSetup.setUp(BaseSetup.java:114)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_0067_submitPlanAndVerifyThatAmazonshipmentIsCreatedWithoutOptimization -->
        <test-method signature="TC_0068_submitPlanAndVerifyThatAmazonshipmentIsCreatedWithOptimization()[pri:0, instance:[POShipmentTestCases passed=0 failed=0 skipped=0]]" started-at="2023-09-28T17:34:18 IST" name="TC_0068_submitPlanAndVerifyThatAmazonshipmentIsCreatedWithOptimization" finished-at="2023-09-28T17:34:18 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Exception occured while invoking browser, Exception message:Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Exception occured while invoking browser, Exception message:Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
at org.testng.Assert.fail(Assert.java:99)
at sc.utilities.BaseSetup.setUp(BaseSetup.java:114)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_0068_submitPlanAndVerifyThatAmazonshipmentIsCreatedWithOptimization -->
        <test-method is-config="true" signature="intialize()[pri:0, instance:[POShipmentTestCases passed=0 failed=0 skipped=0]]" started-at="2023-09-28T17:34:18 IST" name="intialize" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1695902658530" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- intialize -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:[POShipmentTestCases passed=0 failed=0 skipped=0]]" started-at="2023-09-28T17:34:18 IST" name="tearDown" finished-at="2023-09-28T17:34:18 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- sc.testSuite.POShipmentTestCases -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
